# Site settings
title: The Out
client:
  name: The Out
  link: https://www.theout.com/?_branch_match_id=700282973881195500
core-se-link: https://www.secretescapes.com/current-sales
description: >
  This is your chance to indulge in an opulent getaway to the Poets House Hotel in charming Ely, Cambridgeshire. Spend two nights enjoying the boutique style of this gorgeous stay, where period features meet sympathetic contemporary touches. And how to get there? THE OUT has you covered. Delivered to your door and yours for the duration of your escape, the new Range Rover Evoque R-Dynamic, fit for a sumptuous adventure in style and comfort. Explore the gorgeous Cambridgeshire countryside, tackling twisting country lanes as you dip in-and-out of pretty villages.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/the-out" # the subpath of your site, e.g. /blog/
img:     "/the-out/_assets/img"
css:     "/the-out/_assets/css"
js:      "/the-out/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed